server:
  port: 8095
spring:
  application:
    name: msvc-order-detail
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
